export function createInitialUiState({ todayKey, recoveryReady = false }) {
  return {
    drawerOpen: false,
    notificationsOpen: false,
    desktopSearchOpen: false,
    notificationsCleared: false,
    hasVerifiedSession: false,
    searchOpenFrom: "home",
    searchQuery: "",
    foodDate: todayKey,
    foodCalendarOpen: false,
    foodCalendarMonth: todayKey,
    waterHistoryOpen: false,
    waterHistoryDate: todayKey,
    waterHistoryMonth: todayKey,
    modal: null,
    importFlow: {
      target: null,
      file: null,
      fileName: "",
      rawText: "",
      preview: null,
      busy: false,
      error: "",
    },
    selectedPlanId: null,
    selectedConsumedId: null,
    selectedFood: null,
    selectedSupplementId: null,
    selectedTrainingId: null,
    activeTraining: null,
    completedTraining: null,
    trainingDraft: null,
    trainingClock: Date.now(),
    newTrainingExerciseId: null,
    editor: null,
    substituteFood: null,
    confirmAction: null,
    draftGuard: { key: null, dirty: false },
    recoverEmail: "",
    authNotice: "",
    authNoticeTitle: "",
    authNoticeTone: "error",
    authBusy: false,
    toast: null,
    showLoginPassword: false,
    showSignupPassword: false,
    showSignupConfirmPassword: false,
    showResetPassword: false,
    showResetPasswordConfirm: false,
    authReady: false,
    passwordRecoveryReady: recoveryReady,
  };
}
