module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,html}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#c6c6c9",
        "surface-bright": "#fdf6ff",
        "secondary-fixed-dim": "#bbc3ff",
        "on-surface-variant": "#5b6479",
        "tertiary-fixed": "#ffdbd1",
        "outline-variant": "#c5c5d5",
        "inverse-surface": "#2f3131",
        "on-surface": "#1a1c1c",
        "tertiary": "#902200",
        "on-primary": "#ffffff",
        "surface": "#fdf6ff",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-low": "#f3efff",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        secondary: "#778BFF",
        "on-tertiary-container": "#ffd8ce",
        "on-primary-container": "#dfdfe2",
        "inverse-primary": "#c6c6c9",
        "on-secondary-fixed-variant": "#2539aa",
        "surface-variant": "#e6def6",
        "on-tertiary-fixed-variant": "#882000",
        primary: "#494b4d",
        "on-primary-fixed-variant": "#454749",
        background: "#ebf5f2",
        "secondary-container": "#778BFF",
        "on-secondary": "#ffffff",
        "surface-dim": "#efe9fb",
        "surface-container-highest": "#e9e3f7",
        "secondary-fixed": "#dee0ff",
        "surface-tint": "#7b78a6",
        "primary-container": "#616365",
        "on-primary-fixed": "#1a1c1e",
        "on-tertiary-fixed": "#3b0900",
        "surface-container-lowest": "#fffdf8",
        "surface-container": "#efeafc",
        "tertiary-fixed-dim": "#ffb5a1",
        "inverse-on-surface": "#f6f4ff",
        "on-tertiary": "#ffffff",
        outline: "#a9a3c7",
        "primary-fixed": "#e2e2e5",
        "on-background": "#0F172A",
        "surface-container-high": "#ece7fb",
        "on-secondary-container": "#001c8e",
        "tertiary-container": "#b53610",
        "on-secondary-fixed": "#000f5d",
        "jet-black": "#0B1020",
        "royal-blue": "#778BFF",
        "salmon-orange": "#FF931D",
        "purple-recovery": "#778BFF",
        "old-flax": "#DAFF00",
        "custom-purple": "#778BFF",
        "custom-flax": "#DAFF00",
        "custom-orange": "#FF931D",
        "custom-jet": "#292B2D",
        "soft-purple": "#778BFF",
      },
      fontFamily: {
        headline: ["Sora"],
        body: ["Sora"],
        label: ["Sora"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "10px",
        xl: "10px",
        "2xl": "10px",
        "3xl": "10px",
        full: "9999px",
      },
    },
  },
};
