module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,html}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#f2f2f2",
        "surface-bright": "#ffffff",
        "secondary-fixed-dim": "#f2f2f2",
        "on-surface-variant": "#4d4d4d",
        "tertiary-fixed": "#f2f2f2",
        "outline-variant": "#d9d9d9",
        "inverse-surface": "#000000",
        "on-surface": "#000000",
        "tertiary": "#000000",
        "on-primary": "#ffffff",
        "surface": "#ffffff",
        "on-error": "#ffffff",
        "on-error-container": "#000000",
        "surface-container-low": "#f7f7f7",
        "error-container": "#000000",
        error: "#000000",
        secondary: "#000000",
        "on-tertiary-container": "#000000",
        "on-primary-container": "#000000",
        "inverse-primary": "#ffffff",
        "on-secondary-fixed-variant": "#000000",
        "surface-variant": "#f2f2f2",
        "on-tertiary-fixed-variant": "#000000",
        primary: "#000000",
        "on-primary-fixed-variant": "#000000",
        background: "#ffffff",
        "secondary-container": "#000000",
        "on-secondary": "#ffffff",
        "surface-dim": "#f7f7f7",
        "surface-container-highest": "#eeeeee",
        "secondary-fixed": "#f2f2f2",
        "surface-tint": "#000000",
        "primary-container": "#000000",
        "on-primary-fixed": "#000000",
        "on-tertiary-fixed": "#000000",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f7f7f7",
        "tertiary-fixed-dim": "#eeeeee",
        "inverse-on-surface": "#ffffff",
        "on-tertiary": "#ffffff",
        outline: "#666666",
        "primary-fixed": "#f2f2f2",
        "on-background": "#000000",
        "surface-container-high": "#eeeeee",
        "on-secondary-container": "#000000",
        "tertiary-container": "#000000",
        "on-secondary-fixed": "#000000",
        "jet-black": "#000000",
        "royal-blue": "#000000",
        "salmon-orange": "#000000",
        "purple-recovery": "#000000",
        "old-flax": "#000000",
        "custom-purple": "#000000",
        "custom-flax": "#000000",
        "custom-orange": "#000000",
        "custom-jet": "#000000",
        "soft-purple": "#000000",
      },
      fontFamily: {
        headline: ["Sora"],
        body: ["Sora"],
        label: ["Sora"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "10px",
        xl: "10px",
        "2xl": "10px",
        "3xl": "10px",
        full: "9999px",
      },
    },
  },
};
